# Вынесено в отдельную роли, чтоб не было стены плача
---
- name: install components
  apt:
    name: "sshpass"
    update_cache: yes
  loop:
  - ca-certificates
  - curl
  - software-properties-common
  - unzip
...
