---
- name: install setfacl support
  become: yes
  apt: pkg=acl

- name: Create User
  become_user: postgres
  postgresql_user:
   name: "{{ admnPostgres }}"
   password: "{{ PasswordPostgres }}"
   role_attr_flags: SUPERUSER,LOGIN
...
