---
# по другому на астре работает не стабильно, иногда вылетают ошибки вида "apt module not found"
- name: apt update
  apt: update_cache=yes cache_valid_time=3600

- name: install
  apt:
    name: wget
    state: latest

- name: apt update
  apt: update_cache=yes cache_valid_time=3600

- name: backup sources.list
  copy:
    src: /etc/apt/sources.list
    dest: "/home/{{ ansible_user }}/sources.list"
    remote_src: yes

- name: remove sources.list
  file:
    path: /etc/apt/sources.list
    state: absent

- name: touch sources.list
  file:
    path: /etc/apt/sources.list
    state: touch

- name: add repo
  apt_repository:
    repo: deb https://mirror.yandex.ru/debian/ stretch main contrib non-free

# Если все, что было сверху вас не смутило, то сейчас вы увидите то
# чего в природе быть не должно, но имеет место быть

- name: Add PostgreSQL APT repository
  shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list'

# --no-check используется потому-что так надо

- name: Add PostgreSQl key
  shell: wget --no-check-certificate https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -

- name: apt update
  apt: update_cache=yes cache_valid_time=5

- name: Install PostgreSQL 13 & contrib
  apt:
   name: postgresql-13
  loop:
      - "postgresql-contrib"

- name: /etc/apt/sources.list
  copy:
    src: "/home/{{ ansible_user }}/sources.list"
    dest:  /etc/apt/sources.list
    remote_src: yes
...
