---
- name: up
  shell: bash /home/build/do.sh all up

- name: Pause for 2 minutes to build app cache
  pause:
    minutes: 2

- name: bash /home/build/do.sh dt deploy --package --init
  shell: bash /home/build/do.sh dt deploy --package --init

- name: Pause for 3 minutes to build app cache
  pause:
    minutes: 3

- name: import templates
  shell: bash /home/build/do.sh rxcmd import_templates --server="https://"{{ host_fqdn }}"/Integration/odata"
...
